// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwPxVnjPZqoE3olAE7eOs2e7Nbw2Nqel4',
    appId: '1:583374217588:web:4b6fc46c53d046eb998c21',
    messagingSenderId: '583374217588',
    projectId: 'projrj',
    authDomain: 'projrj.firebaseapp.com',
    storageBucket: 'projrj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWL9wAFv55VWkC28dZSLMm9QfzWELlIKA',
    appId: '1:583374217588:android:99b9c5600baf1331998c21',
    messagingSenderId: '583374217588',
    projectId: 'projrj',
    storageBucket: 'projrj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqlKU-_qh7TmS-UjdveVRlW5Ux2If0Bio',
    appId: '1:583374217588:ios:49ee36580424b9be998c21',
    messagingSenderId: '583374217588',
    projectId: 'projrj',
    storageBucket: 'projrj.appspot.com',
    androidClientId: '583374217588-g2nk3k7bqjkmu1jrtrddali6g2u5pek5.apps.googleusercontent.com',
    iosClientId: '583374217588-33avcf9a3al81cepf4o9egsj59ridjmk.apps.googleusercontent.com',
    iosBundleId: 'com.edwin.rj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqlKU-_qh7TmS-UjdveVRlW5Ux2If0Bio',
    appId: '1:583374217588:ios:49ee36580424b9be998c21',
    messagingSenderId: '583374217588',
    projectId: 'projrj',
    storageBucket: 'projrj.appspot.com',
    androidClientId: '583374217588-g2nk3k7bqjkmu1jrtrddali6g2u5pek5.apps.googleusercontent.com',
    iosClientId: '583374217588-33avcf9a3al81cepf4o9egsj59ridjmk.apps.googleusercontent.com',
    iosBundleId: 'com.edwin.rj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwPxVnjPZqoE3olAE7eOs2e7Nbw2Nqel4',
    appId: '1:583374217588:web:540432824b31b188998c21',
    messagingSenderId: '583374217588',
    projectId: 'projrj',
    authDomain: 'projrj.firebaseapp.com',
    storageBucket: 'projrj.appspot.com',
  );
}
